### ISSUE TITLE
Move Refactorings are not tracked

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#165]
The process metrics test for toyrepo 07 (#163 ) showed, that move source refactorings are not tracked by the ProcessMetricsTracker.

**Comment by jan-gerling** [comment]
Fixing this issue is actually quite difficult:

 1. **JGit** does **not detect** (some) move and all move source dir refactorings, but RMiner does
 1.  JGit does not generate diffentries for these cases, thus we cannot update the process metrics correctly

**Solution:**
 1. ignore line deletions and additions in move refactorings 
 1. Reorder the entire commit processing:
   1.  Collect process metrics already while processing refactorings
   1. update the PMDatabase while processing refactorings
   1. only detect and store stable commits in ProcessMetricsCollector (rename it then)

**Comment by mauricioaniche** [comment]
Hi, Jan! I'm not sure if I understand it. RMiner identifies the refactoring. The refactoring then goes to the `allRefactoringCommits` variable in `App:processCommit`. Then, we call `processMetrics.collectMetrics`, passing the list of refactorings. 

Why can't you collect the metrics for all the refactorings there? I'm having the feeling it's because the name of the files are not matching. Am I right? If so, maybe you will have to do like I did, see `getMapWithOldAndNewFiles()` method in `RefactoringAnalyzer`.

We definitely know that the class suffered a refactoring, so I suppose all we need to do is to find the diff entry related to it. 

Shall we talk in person about it? You walk me through the case, so that I can maybe help you a bit more?

**Comment by mauricioaniche** [comment]
How's this issue going?
